language: csharp
solution: DnDGen.Stress.sln
mono: none
dotnet: 3.1

script:
  - dotnet build ./DnDGen.Stress/DnDGen.Stress.csproj -c Release
    && dotnet test ./DnDGen.Stress.Tests/DnDGen.Stress.Tests.csproj
  - dotnet build ./DnDGen.Stress.Events/DnDGen.Stress.Events.csproj -c Release
    && dotnet test ./DnDGen.Stress.Events.Tests/DnDGen.Stress.Events.Tests.csproj
deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy/deploy.sh && ./deploy/deploy.sh $NUGET_API_KEY $NUGET_SOURCE
  on:
    branch: master
matrix:
  fast_finish: true
