# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.Stress.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './DnDGen.Stress/DnDGen.Stress.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: './DnDGen.Stress.Tests/DnDGen.Stress.Tests.csproj'
    arguments: '-v normal'

- task: NuGetCommand@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Push NuGet Package   
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: './DnDGen.Stress/**/*.nupkg'
    externalFeedCredentials: 'NuGet.org'
    
- task: GithubRelease@0 
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Create GitHub Release
  inputs:
    gitHubConnection: github.com_cidthecoatrack  
    assets: './DnDGen.Stress/**/*.nupkg'
    title: '$(Major).$(Minor).$(rev:.r)'