# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master
- develop

pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.Stress.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './DnDGen.Stress/DnDGen.Stress.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: './DnDGen.Stress.Tests/DnDGen.Stress.Tests.csproj'
    arguments: '-v normal'

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: Publish Artifacts
  inputs:
    pathtoPublish: './DnDGen.Stress' 
    artifactName: 'dndgen-stress'

- task: tmarkovski.projectversionasvariable.versionintovariable.projectversionasvariable@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  displayName: 'Get Project Version'
  inputs:
    path: ./DnDGen.Stress/DnDGen.Stress.csproj
    
- script: |
     echo "Tagging with version $(Version.MajorMinorBuild)"
     git tag $(Version.MajorMinorBuild)
     git push origin $(Version.MajorMinorBuild)
  workingDirectory: $(Build.SourcesDirectory)