pool:
  vmImage: 'windows-latest'

variables:
  solution: 'DnDGen.Stress.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'


steps:
- checkout: self
  displayName: 'Checkout Code'
  persistCredentials: true
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: './DnDGen.Stress/DnDGen.Stress.csproj'
    arguments: '--configuration $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: Run Unit Tests
  inputs:
    command: test
    projects: './DnDGen.Stress.Tests/DnDGen.Stress.Tests.csproj'
    arguments: '-v normal --configuration Stress'

- task: PowerShell@2
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'Get Project Version'
  inputs:
    targetType: 'inline'
    script: |
         $xml = [Xml] (Get-Content ./DnDGen.Stress/DnDGen.Stress.csproj)
         $version = $xml.Project.PropertyGroup.Version
         echo $version
         echo "##vso[task.setvariable variable=version]$version"
    
- script: |
     echo "Tagging with version $(version)"
     git tag $(version)
     git push origin $(version)
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: 'Tag Version'
  workingDirectory: $(Build.SourcesDirectory)

- task: PublishBuildArtifacts@1
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/main'))
  displayName: Publish Artifacts
  inputs:
    pathtoPublish: './DnDGen.Stress/bin/Release' 
    artifactName: 'dndgen-stress'
